swagger: "2.0"
info:
  description: "REST API to provide information of UFC fights and fighters."
  version: "1.0.0"
  title: "UFC API"
  contact:
    email: "tai.okubo93@gmail.com"
host: "www.api.ufc.com"
basePath: "/v2"
tags:
- name: "fighters"
  description: "Operations about fighters"
paths:
  /fighters:
    get:
      tags:
      - "fighters"
      summary: "Retrieves a list with all fighters"
      operationId: "findAll"
      parameters:
      - name: "Content-Type"
        in: "header"
        description: "The acceptable format"
        required: true
        type: "string"
      - name: "offset"
        in: "query"
        description: "The number of items to skip before starting to collect the result set"
        type: "integer"
      - name: "limit"
        in: "query"
        description: "The numbers of items to return"
        type: "integer"
      produces:
      - "application/vnd.api+json"
      responses:
        200:
          description: "Successfully retrieves the required resource"
          schema:
            $ref: "#/definitions/FighterListResponse"
        401:
          description: "You are not authorized to view the resource"
        403:
          description: "Accessing the resource you are trying to access is forbidden"
        404:
          description: "The resource you are trying to access was not found"
      security:
      - api_key: []

    post:
      tags:
      - "fighters"
      summary: "Adds a new fighter"
      consumes:
      - "application/vnd.api+json"
      produces:
      - "application/vnd.api+json"
      parameters:
      - name: "Content-Type"
        in: "header"
        description: "application/vnd.api+json"
        required: true
        type: "string"
      - in: "body"
        name: "Request"
        description: "Saves a new fighter in the database"
        required: true
        schema:
          $ref: "#/definitions/FighterRequest"
      responses:
        202:
          description: "The resource sent was accepted"
          schema:
            $ref: "#/definitions/FighterResponse"
        401:
          description: "You are not authorized to view the resource"
        403:
          description: "Accessing the resource you are trying to access is forbidden"
        404:
          description: "The resource you are trying to access was not found"

      security:
      - api_key: []

  /fighters/{id}:
    get:
      tags:
      - "fighters"
      summary: "Finds fighters with the given id"
      produces:
      - "application/vnd.api+json"
      parameters:
      - name: "Content-Type"
        in: "header"
        description: "application/vnd.api+json"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        description: "ID of fighter to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successfully retrieves the required resource"
          schema:
            $ref: "#/definitions/FighterResponse"
        401:
          description: "You are not authorized to view the resource"
        403:
          description: "Accessing the resource you are trying to access is forbidden"
        404:
          description: "The resource you are trying to access was not found"
      security:
      - api_key: []

    patch:
      tags:
      - "fighters"
      summary: "Update the informations of the fighter with the given id"
      consumes:
      - "application/vnd.api+json"
      produces:
      - "application/vnd.api+json"
      parameters:
      - name: "Content-Type"
        in: "header"
        description: "application/vnd.api+json"
        required: true
        type: "string"
      - in: "body"
        name: "Request"
        description: "Request object that follows Json API specification"
        required: true
        schema:
          $ref: "#/definitions/FighterRequest"
      - name: "id"
        in: "path"
        description: "ID of fighter to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successfully retrieves the required resource"
          schema:
            $ref: "#/definitions/FighterResponse"
        401:
          description: "You are not authorized to view the resource"
        403:
          description: "Accessing the resource you are trying to access is forbidden"
        404:
          description: "The resource you are trying to access was not found"
      security:
      - api_key: []

    delete:
      tags:
      - "fighters"
      summary: "Deletes the fighter with the given id"
      produces:
      - "application/vnd.api+json"
      parameters:
      - name: "Content-Type"
        in: "header"
        description: "application/vnd.api+json"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        description: "ID of fighter to remove"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successfully removed the resource"
          schema:
            $ref: "#/definitions/FighterResponse"
        404:
          description: "The resource you are trying to remove was not found"
      deprecated: false
      security:
      - api_key: []

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  FighterRequest:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/FighterData"

  FighterListRequest:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/FighterListData"

  FighterResponse:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/FighterData"
      meta:
        $ref: "#/definitions/RequestMeta"

  FighterListResponse:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/FighterListData"
      meta:
        $ref: "#/definitions/RequestMeta"

  FighterData:
    type: "object"
    properties:
      attributes:
        $ref: "#/definitions/Fighter"

  FighterListData:
    type: "object"
    properties:
      attributes:
        type: array
        items:
          $ref: "#/definitions/Fighter"

  RequestMeta:
    type: "object"
    properties:
      authors:
        type: "array"
        items:
          type: "string"


  Fighter:
    type: "object"
    properties:
      first_name:
        type: "string"
      last_name:
        type: "string"
      nickname:
        type: "string"
      holds_title:
        type: "boolean"
      weight_classes:
        type: "string"
      winnings:
        type: "integer"
        format: "int32"
      losses:
        type: "integer"
        format: "int32"
      draws:
        type: "integer"
        format: "int32"
      height:
        type: "string"
      weight:
        type: "string"
      sumarry:
        type: "string"
  Errors:
    type: "object"
    properties:
      errors:
        type: "array"
        items:
          type: "string"
      status:
        type: "string"
      detail:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"